In [10]:
import os
import pandas as pd
import numpy as np
import re
from datetime import datetime
import arrow
import numpy as np
import netCDF4 as nc
import pandas as pd
import numpy.ma as ma
import matplotlib as mpl
import matplotlib.pyplot as pltz
import xarray as xar
import rioxarray

## 比较 `reindex` 与 [x] 的方式的降序排列的方式


使用 `xarray.Dataset.reindex` 的方式实现降序排列,  
[xarray.DataArray.reindex](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.reindex.html),  
[xarray.Dataset.reindex](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.reindex.html)

### 1-1 使用 `xarray.Dataset.reindex` 的方式实现对于某个维度降序排列  
看出对某个维度降序排列，且数据也根据维度的索引变化也发生了变化，相当于只是`降序`

In [11]:
da = xar.DataArray(
    np.arange(4),
    coords=[np.array([90, 89, 88, 87])],
    dims="lat",
)
da

<xarray.DataArray (lat: 4)>
array([0, 1, 2, 3])
Coordinates:
  * lat      (lat) int32 90 89 88 87

In [15]:
da.lat[::-1]

<xarray.DataArray 'lat' (lat: 4)>
array([90, 89, 88, 87])
Coordinates:
  * lat      (lat) int32 90 89 88 87

In [12]:
da.reindex(lat=da.lat[::-1])

<xarray.DataArray (lat: 4)>
array([3, 2, 1, 0])
Coordinates:
  * lat      (lat) int64 87 88 89 90

### 1-2 使用直接赋值的方式进行降序  
使用此种方式实际是`维度索引-index`保持不变，而调换了其中的`值`

In [13]:
da['lat']=da['lat'][::-1]
da

<xarray.DataArray (lat: 4)>
array([0, 1, 2, 3])
Coordinates:
  * lat      (lat) int32 87 88 89 90

----  
尝试创建一个 dataset 对象

In [18]:
# 尝试创建一个 dataset 对象
x = xar.Dataset(
    {
        "temperature": ("station", [10,11,12,13]),
        "pressure": ("station", [101,102,103,104]),
    },
    coords={"station": ["a", "b", "c", "d"]},
)
x

<xarray.Dataset>
Dimensions:      (station: 4)
Coordinates:
  * station      (station) <U1 'a' 'b' 'c' 'd'
Data variables:
    temperature  (station) int32 10 11 12 13
    pressure     (station) int32 101 102 103 104

In [19]:
x.reindex(station=x.station[::-1])

<xarray.Dataset>
Dimensions:      (station: 4)
Coordinates:
  * station      (station) object 'd' 'c' 'b' 'a'
Data variables:
    temperature  (station) int32 13 12 11 10
    pressure     (station) int32 104 103 102 101

In [20]:
x['station']=x['station'][::-1]

In [21]:
x

<xarray.Dataset>
Dimensions:      (station: 4)
Coordinates:
  * station      (station) <U1 'd' 'c' 'b' 'a'
Data variables:
    temperature  (station) int32 10 11 12 13
    pressure     (station) int32 101 102 103 104